spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
config:
  secret-key: ${JWT_KEY}
  token-validity-time: PT30M
  stripe-secret-key: ${STRIPE_SECRET_KEY}
  client-host-url: ${CLIENT_HOST_URL}
  google-client-secret: ${GOOGLE_CLIENT_SECRET}
  google-client-id: ${GOOGLE_CLIENT_ID}
