spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
config:
  secret-key: ${JWT_KEY}
  token-validity-time: PT30M
  stripe-secret-key: ${STRIPE_SECRET_KEY}
  stripe-publishable-key: pk_test_51OJiuVEfP6399Oje8fDMxfcJMQNyUKGidLPaPzmfXg1fJpCsjsqz4Gs5DlTDpvI9psyhPI25DKnVMoJkyncwUvLP00snZUpRqo
  client-host-url: http://localhost:5173
